import type { LucideIcon } from "lucide-react-native";
import {
  UtensilsCrossed,
  Building2,
  Camera,
  Video,
  Music,
  Flower2,
  ClipboardList,
  User,
  Scissors,
  Car,
  Bus,
  Cake,
  Aperture,
  Smile,
  Mail,
  Box,
  Hotel,
  Shirt,
  ShieldCheck,
  Ellipsis,
} from "lucide-react-native";
import type { VendorType } from "@fiance/sdk";

export const VENDOR_TYPE_ICONS: Record<VendorType, LucideIcon> = {
  CATERER: UtensilsCrossed,
  VENUE: Building2,
  PHOTOGRAPHER: Camera,
  VIDEOGRAPHER: Video,
  DJ: Music,
  BAND: Music,
  FLORIST: Flower2,
  WEDDING_PLANNER: ClipboardList,
  OFFICIANT: User,
  HAIR_MAKEUP: Scissors,
  TRANSPORT: Car,
  SHUTTLE: Bus,
  CAKE: Cake,
  PHOTO_BOOTH: Aperture,
  KIDS_ENTERTAINER: Smile,
  STATIONERY: Mail,
  FURNITURE_RENTAL: Box,
  HOTEL: Hotel,
  CLOTHING: Shirt,
  SECURITY: ShieldCheck,
  OTHER: Ellipsis,
};
